### ISSUE TITLE
[EPIC] Osmosis-installer refactoring 

### ISSUE THREAD

**Issue by stackman27** [osmosis-labs/osmosis-installer#50]
Refactoring Osmosis-installer 

**-Code Cleanup & Tests**
   -  Cleanup deduplication 
         - [ ] start a proper folder structure and breakdown functions  
         - [ ] have single file for all print statements and use it as variable across many files 
         - [ ] have single file that dictates the overall style of the installer
         - [ ] Create simple script that will merge all script in single file from different files  [Issue: #20]
   -  Docker testing suites  [Issue:  #43]
         - [ ] TBD what specific functions to test 
         - [ ] add unittesting for applicable functions

**-UX improvement** 
   - [ ] Ask all question at once before proceeding with any of the downloading installation [Issue: #29] 

**-Code Automation**
   - [ ] Automate go version upload [Issue:  #42] 
   - [ ] Automation that utilizes flags to ensure a node is able to hit blocks when starting from scratch [#32]
   - [ ] Automate updating config based on [chain.schema.json](https://github.com/osmosis-labs/osmosis/blob/main/chain.schema.json)

**Comment by p0mvn** [comment]
Would like to suggest this change to be added as well as making this a suggested download location: https://github.com/osmosis-labs/osmosis-installer/issues/55
